### ISSUE TITLE
Infinite Loop with the Knight

### ISSUE THREAD

**Issue by coreykovoch** [krissteinort/adventuregame#3]
I was just messing around and I found a loop involving the Knight that allows you to continue and make the same choices over and over and over. 

You pretty much just keep looping back to asking him `who he is` and repeating. 

I just included the screenshots but if you want me to elaborate on anything or need me to clarify, let me know.

![image](https://user-images.githubusercontent.com/15265996/56662000-f7b95780-6670-11e9-8949-3850fa2da76d.png)

![image](https://user-images.githubusercontent.com/15265996/56662009-fbe57500-6670-11e9-87a7-8e1123ebdf0b.png)

![image](https://user-images.githubusercontent.com/15265996/56662017-ff78fc00-6670-11e9-98a2-ac04d8bf9557.png)

![image](https://user-images.githubusercontent.com/15265996/56662022-043db000-6671-11e9-9eca-55980f71347a.png)

![image](https://user-images.githubusercontent.com/15265996/56662032-0738a080-6671-11e9-9057-b81633cc5f5a.png)

![image](https://user-images.githubusercontent.com/15265996/56662043-0acc2780-6671-11e9-9f9a-a5b3099dfdcc.png)

![image](https://user-images.githubusercontent.com/15265996/56662047-0d2e8180-6671-11e9-83c7-6e537786cd13.png)

![image](https://user-images.githubusercontent.com/15265996/56662092-2cc5aa00-6671-11e9-896d-3454647fea9b.png)

![image](https://user-images.githubusercontent.com/15265996/56662103-35b67b80-6671-11e9-93b0-f0c44eb0f786.png)

![image](https://user-images.githubusercontent.com/15265996/56662120-44049780-6671-11e9-8229-b0e319a5de83.png)

**Comment by krissteinort** [comment]
Removed "Who are you?" from second knight option with 7244561b6c2c7f1dbe237ab7aa07f748d2c6928c should be fixed now! Thanks.
